### ISSUE TITLE
pip install http does not work

### ISSUE THREAD

**Issue by vreyespue** [franckcuny/http#3]
Hi, somehow the pip installation does not work. I tried in several machines/environments (some of them with a clean new python installation, i.e. virtual machines etc.) without success.
Did I misunderstand something? Is the pip package broken? Or is it compatible only with specific python versions?
Below you can find the result of the install command (similar in all tested machines/environments).
Many thanks and best regards.
```
$ python --version
Python 3.7.10

$ pip -V
pip 21.1.2 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)

$ pip install http
Collecting http
  Using cached http-0.02.tar.gz (32 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3zlfy15o/http_b5ae03f6af6f42f48ad94c016c2da1e9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3zlfy15o/http_b5ae03f6af6f42f48ad94c016c2da1e9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bhz5u2k2
         cwd: /tmp/pip-install-3zlfy15o/http_b5ae03f6af6f42f48ad94c016c2da1e9/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3zlfy15o/http_b5ae03f6af6f42f48ad94c016c2da1e9/setup.py", line 3, in <module>
        import http
      File "/tmp/pip-install-3zlfy15o/http_b5ae03f6af6f42f48ad94c016c2da1e9/http/__init__.py", line 17, in <module>
        from request import Request
    ModuleNotFoundError: No module named 'request'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e3/91/a9260805e532e33df273b8f7dffad5c51693f8f9ba5f86bedcf42a7f22eb/http-0.02.tar.gz#sha256=071bc409f687535b6e31a94bced6a7773905abad8d2f236b406202b7283f682c (from https://pypi.org/simple/http/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached http-0.1.tar.gz (31 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3zlfy15o/http_8ed447f373594df388568a58988b3df9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3zlfy15o/http_8ed447f373594df388568a58988b3df9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-irxw9dtk
         cwd: /tmp/pip-install-3zlfy15o/http_8ed447f373594df388568a58988b3df9/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3zlfy15o/http_8ed447f373594df388568a58988b3df9/setup.py", line 3, in <module>
        import http
      File "/tmp/pip-install-3zlfy15o/http_8ed447f373594df388568a58988b3df9/http/__init__.py", line 17, in <module>
        from request import Request
    ModuleNotFoundError: No module named 'request'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/71/f0/787d609561ada283d6755e6f1198aa65a6eea075297725344e8f8c12eb03/http-0.1.tar.gz#sha256=0e66b52fc46640edd547c3c47a7913e0c5f76a69db6fb09e7b48c5f7866b2c37 (from https://pypi.org/simple/http/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement http (from versions: 0.1, 0.2)
ERROR: No matching distribution found for http

**Comment by vreyespue** [comment]
ups sorry, I just read the documentation that at the moment the only way to install is from github 👍 
https://http.readthedocs.io/en/latest/install.html
I will create a small PR to update the Readme accordingly 👍

**Comment by vreyespue** [comment]
As shown in #5, it works for Python 2 but not for higher versions of Python 3.
